export const ORDER_STATUSES_PENDING = "PENDING";
export const ORDER_STATUSES_CONFORMED = "CONFORMED";
export const ORDER_STATUSES_SHIPPED = "SHIPPED";
export const ORDER_STATUSES_DELIVERED = "DELIVERED";
